In [5]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = pd.read_csv("Airline_Delay_Cause.csv")
data

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2023,8,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",89.0,13.0,2.25,1.60,...,0.0,5.99,2.0,1.0,1375.0,71.0,761.0,118.0,0.0,425.0
1,2023,8,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",62.0,10.0,1.97,0.04,...,0.0,7.42,0.0,1.0,799.0,218.0,1.0,62.0,0.0,518.0
2,2023,8,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",62.0,10.0,2.73,1.18,...,0.0,4.28,1.0,0.0,766.0,56.0,188.0,78.0,0.0,444.0
3,2023,8,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",66.0,12.0,3.69,2.27,...,0.0,1.57,1.0,1.0,1397.0,471.0,320.0,388.0,0.0,218.0
4,2023,8,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",92.0,22.0,7.76,0.00,...,0.0,11.28,2.0,0.0,1530.0,628.0,0.0,134.0,0.0,768.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171661,2013,8,YV,Mesa Airlines Inc.,TRI,"Bristol/Johnson City/Kingsport, TN: Tri Cities",7.0,1.0,0.78,0.00,...,0.0,0.00,0.0,0.0,23.0,18.0,0.0,5.0,0.0,0.0
171662,2013,8,YV,Mesa Airlines Inc.,YUM,"Yuma, AZ: Yuma MCAS/Yuma International",2.0,1.0,0.00,0.00,...,0.0,1.00,0.0,0.0,17.0,0.0,0.0,0.0,0.0,17.0
171663,2013,8,YV,Mesa Airlines Inc.,SLC,"Salt Lake City, UT: Salt Lake City International",2.0,0.0,0.00,0.00,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
171664,2013,8,DL,Delta Air Lines Inc.,SBN,"South Bend, IN: South Bend International",1.0,1.0,1.00,0.00,...,0.0,0.00,0.0,0.0,18.0,18.0,0.0,0.0,0.0,0.0
171665,2013,8,F9,Frontier Airlines Inc.,MTJ,"Montrose/Delta, CO: Montrose Regional",1.0,0.0,0.00,0.00,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
data.columns.values

array(['year', 'month', 'carrier', 'carrier_name', 'airport',
       'airport_name', 'arr_flights', 'arr_del15', 'carrier_ct',
       'weather_ct', 'nas_ct', 'security_ct', 'late_aircraft_ct',
       'arr_cancelled', 'arr_diverted', 'arr_delay', 'carrier_delay',
       'weather_delay', 'nas_delay', 'security_delay',
       'late_aircraft_delay'], dtype=object)

In [4]:
df_baysian = data.drop(columns=['carrier', 'airport_name', 'nas_ct'])
df_baysian

,year,month,carrier_name,airport,arr_flights,arr_del15,carrier_ct,weather_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2023,8,Endeavor Air Inc.,ABE,89.0,13.0,2.25,1.60,0.0,5.99,2.0,1.0,1375.0,71.0,761.0,118.0,0.0,425.0
1,2023,8,Endeavor Air Inc.,ABY,62.0,10.0,1.97,0.04,0.0,7.42,0.0,1.0,799.0,218.0,1.0,62.0,0.0,518.0
2,2023,8,Endeavor Air Inc.,AEX,62.0,10.0,2.73,1.18,0.0,4.28,1.0,0.0,766.0,56.0,188.0,78.0,0.0,444.0
3,2023,8,Endeavor Air Inc.,AGS,66.0,12.0,3.69,2.27,0.0,1.57,1.0,1.0,1397.0,471.0,320.0,388.0,0.0,218.0
4,2023,8,Endeavor Air Inc.,ALB,92.0,22.0,7.76,0.00,0.0,11.28,2.0,0.0,1530.0,628.0,0.0,134.0,0.0,768.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171661,2013,8,Mesa Airlines Inc.,TRI,7.0,1.0,0.78,0.00,0.0,0.00,0.0,0.0,23.0,18.0,0.0,5.0,0.0,0.0
171662,2013,8,Mesa Airlines Inc.,YUM,2.0,1.0,0.00,0.00,0.0,1.00,0.0,0.0,17.0,0.0,0.0,0.0,0.0,17.0
171663,2013,8,Mesa Airlines Inc.,SLC,2.0,0.0,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
171664,2013,8,Delta Air Lines Inc.,SBN,1.0,1.0,1.00,0.00,0.0,0.00,0.0,0.0,18.0,18.0,0.0,0.0,0.0,0.0
171665,2013,8,Frontier Airlines Inc.,MTJ,1.0,0.0,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
df_baysian.to_csv('cleanedbaysian.csv')

In [ ]:
scaler = MinMaxScaler(feature_range=(1, 5))

df_columns = data[['carrier_name', 'airport', 'arr_delay']]
df_cleaned = df_columns.dropna()
df_cleaned['arr_delay'] = scaler.fit_transform(df_cleaned[['arr_delay']])
df_cf = df_cleaned.pivot_table(index='airport', columns='carrier_name', aggfunc='mean', values='arr_delay')
df_cf

/var/folders/lk/6h869p7n1b99f3frypnq0m_r0000gn/T/ipykernel_57671/2173789603.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['arr_delay'] = scaler.fit_transform(df_cleaned[['arr_delay']])

carrier_name,AirTran Airways Corporation,Alaska Airlines Inc.,Allegiant Air,American Airlines Inc.,American Eagle Airlines Inc.,Delta Air Lines Inc.,Endeavor Air Inc.,Envoy Air,ExpressJet Airlines Inc.,ExpressJet Airlines LLC,...,JetBlue Airways,Mesa Airlines Inc.,PSA Airlines Inc.,Republic Airline,SkyWest Airlines Inc.,Southwest Airlines Co.,Spirit Air Lines,US Airways Inc.,United Air Lines Inc.,Virgin America
airport,,,,,,,,,,,,,,,,,,,,,
ABE,NaN,NaN,1.016745,NaN,NaN,1.001880,1.004191,1.003327,1.011930,1.001876,...,NaN,1.002492,1.00689,1.00144,1.008771,NaN,NaN,NaN,NaN,NaN
ABI,NaN,NaN,NaN,NaN,1.018533,NaN,NaN,1.014023,1.003907,NaN,...,NaN,NaN,NaN,NaN,1.006617,NaN,NaN,NaN,NaN,NaN
ABQ,NaN,1.002206,1.001600,1.023498,1.013778,1.006996,NaN,1.004994,1.004909,1.002299,...,1.003895,1.017481,NaN,1.00202,1.023064,1.082325,1.003747,1.000862,1.010813,NaN
ABR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.004763,NaN,NaN,NaN,NaN,NaN
ABY,NaN,NaN,NaN,NaN,NaN,NaN,1.004115,NaN,1.008733,NaN,...,NaN,NaN,NaN,NaN,1.009801,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XWA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.012461,NaN,NaN,NaN,NaN,NaN
YAK,NaN,1.003600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YKM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YNG,NaN,NaN,1.001085,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YUM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.001207,NaN,NaN,...,NaN,1.004262,NaN,NaN,1.009881,NaN,NaN,NaN,NaN,NaN

In [9]:
df_cf.to_csv('cleanedcf.csv')